version: '1.0'
name: 'lovelystay-cli'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lovelystay-cli
    volumes:
      - postgres_master_data:/var/lib/postgresql/data

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.20.0
    restart: no
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=postgres port=5432 user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME}
      - GOOSE_VERBOSE=true
      #- GOOSE_COMMAND=down # Uncomment this line to run the down command
    volumes:
      - ./database/migrations:/migrations:ro

volumes:
  postgres_master_data:
    driver: local
