-- +goose up
create schema lovely;


create table "lovely.users" (
    "id" int generated by default as identity primary key,
    "user_name" text not null,
    "name" text,
    "location" text not null,
    "html_url" text,
    "repos_url" text,
    constraint "uq_users_user_name" unique (user_name)
);


create table "lovely.languages" (
    "id" int generated by default as identity primary key,
    "name" text not null,
    constraint "uq_languages_name" unique (name)
);


create table "lovely.user_languages" ("user_id" integer, "language_id" integer);


alter table "lovely.user_languages"
add foreign key ("user_id") references "lovely.users" ("id");


alter table "lovely.user_languages"
add foreign key ("language_id") references "lovely.languages" ("id");