-- +goose up
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL,
    name TEXT,
    location TEXT NOT NULL,
    html_url TEXT,
    repos_url TEXT,
    CONSTRAINT uq_users_user_name UNIQUE (user_name)
);


CREATE TABLE languages (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    CONSTRAINT uq_languages_name UNIQUE (name)
);


CREATE TABLE user_languages (user_id INTEGER, language_id INTEGER);


ALTER TABLE user_languages
ADD FOREIGN KEY (user_id) REFERENCES users (id);


ALTER TABLE user_languages
ADD FOREIGN KEY (language_id) REFERENCES languages (id);


-- +goose down
DROP TABLE if EXISTS user_languages;


DROP TABLE IF EXISTS languages;


DROP TABLE IF EXISTS users;