-- +goose up
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login TEXT NOT NULL,
    name TEXT,
    location TEXT NOT NULL,
    html_url TEXT,
    repos_url TEXT,
    CONSTRAINT uq_users_login UNIQUE (login)
);


CREATE TABLE languages (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    CONSTRAINT uq_languages_name UNIQUE (name)
);


CREATE TABLE user_languages (
    user_id INTEGER,
    language_id INTEGER,
    CONSTRAINT uq_user_languages UNIQUE (user_id, language_id)
);


ALTER TABLE user_languages
ADD FOREIGN KEY (user_id) REFERENCES users (id);


ALTER TABLE user_languages
ADD FOREIGN KEY (language_id) REFERENCES languages (id);


-- +goose down
DROP TABLE if EXISTS user_languages;


DROP TABLE IF EXISTS languages;


DROP TABLE IF EXISTS users;